### ISSUE TITLE
Making it work nicely on a dynamically generated html

### ISSUE THREAD

**Issue by rbresson** [dallaslu/bootstrap-4-multi-level-dropdown#2]
Hi, 
Thank you for you code. I like it. It is concise and effective !
However I have a problem with using it on dynamically created html tags (with javascript) unlike your example.
I'm quite new to javascript and will try to be clear.
I have a html file with almost no tag and a call to a javascript file which creates the tag (reading a json file). I realized I need your code to be executed once the tags (the dropdowns) have been generated. Moreover I want your code to be available to several pages without having to duplicate it. 
What would be the best way ?

Thank you
Raphael

**Comment by dallaslu** [comment]
I'm glad to get the feedback. 

The `on` method of jQuery has an optional parameter `childSelector`.

Just change:

`$('.dropdown [data-toggle="dropdown"]').on('click', function(e) {/*...*/})`

to:

`$('.your-root-element').on('click', '.dropdown [data-toggle="dropdown"]', function(e) {/*...*/})`
